IssaHanou/BEP_1920_Q2

back-end/src/config/config.go, back-end/src/config/config_test.go, back-end/src/main/main.go
Needs config in order to make Github path instead of a relative path
=> Added config

back-end/src/sciler/main.go, cc_library/src/sciler/scclib/app.py, cc_library/src/sciler/scclib/logger.py, cc_library/src/scripts/controlboard.py, cc_library/src/scripts/door.py
Closes GH-33
Creates logger file in client computer library. All logging is handled through here, which is property of SccLib class. It logs to both cmd and file.
=> Adds logger to client computer

.gitignore, back-end/resources/room_config.json, back-end/src/sciler/handler/handler.go, back-end/src/sciler/main.go, broker/README.md, broker/local.conf, cc_library/src/sciler/scclib/app.py, cc_library/src/sciler/scclib/logger.py, cc_library/src/scripts/controlboard.py, cc_library/src/scripts/controlboard_config.json, cc_library/src/scripts/display.py, cc_library/src/scripts/display_config.json, cc_library/src/scripts/door_config.json, front-end/src/app/app.component.ts, front-end/src/app/components/hint/hint.component.spec.ts, front-end/src/app/components/hint/hint.component.ts
Changed all topics to:
front-end (message to frontend)
back-end (message to backend)
client/device.name(/hint) (message to client)
Also implemented a hint device and send the hints from the front-end properly through the system.
Closes GH-79
GH-28 and GH-37 have a starting implementation
=> 79 broker topics

front-end/src/app/app.component.ts, front-end/src/app/components/hint/hint.component.ts, front-end/src/app/components/manage/manage.component.ts
The sendInstruction method in app.component should be general method to send instructions. 
- It can now take several instructions
- it allows for additional tags on an instruction
=> resturctured send instruction, hint also uses general method

back-end/src/sciler/handler/handler.go, back-end/src/sciler/handler/handler_test.go, cc_library/src/scripts/controlboard.py
Status messages now get properly type-checked with the config before setting the status
Closes GH-83
=> 83 typechecking status

back-end/resources/room_config.json, cc_library/src/sciler/scclib/app.py, cc_library/src/sciler/scclib/device.py, cc_library/src/sciler/scclib/test_device.py, cc_library/src/scripts/controlboard.py, cc_library/src/scripts/display.py, cc_library/src/scripts/door.py
get_status should now return a dictionary instead of JSON in string form
GH-92
=> updated status

back-end/src/sciler/handler/handler.go, front-end/src/app/app.component.ts, front-end/src/app/components/timer/timer.component.ts, front-end/src/app/components/timer/timer.spec.ts, front-end/src/app/components/timer/timer.ts, front-end/src/app/components/timer/timers.spec.ts, front-end/src/app/components/timer/timers.ts
Timer has now be restructured to be more like devices, now it will be easier to show all timers in the front-end in a later stage
=> 109 timer fixes

back-end/resources/message_manual.md, back-end/resources/room_manual.md, broker/README.md, cc_library/src/sciler/README.md, cc_library/src/sciler/device_manual.md
=> 112 update manuals

back-end/resources/demo_config.json, back-end/resources/room_config.json
closes GH-123
With this action added to the stop event, the time does stop in the front-end (and back-end)
=> General timer stops on stop

front-end/src/app/app.module.ts, front-end/src/app/components/device/device.component.css, front-end/src/app/components/device/device.component.html, front-end/src/app/components/device/device.component.spec.ts, front-end/src/app/components/device/device.component.ts, front-end/src/app/components/puzzle/puzzle.component.spec.ts
Closes GH-129
When clicking a device in the table, the components collapse/unfold
=> 129 collapse

.gitignore, back-end/resources/hue_config.json, back-end/resources/room_manual.md, back-end/src/sciler/config/readConfigTypes.go, back-end/src/sciler/config/workingConfigTypes.go, back-end/src/sciler/handler/handler_helper.go, back-end/src/sciler/handler/handler_test.go
Closes GH-107
Actions now have an option to add a "delay":"XhXmXs" to the json array. 
When an action has a delay, a go-routine will start that first sleeps XhXmXs and then publishes the action.
=> 107 delay optimize

back-end/resources/manuals/room_manual.md, back-end/resources/production/room_config.json.default, back-end/resources/testing/test_instruction_label.json, back-end/resources/testing/wrong-types/testCheckLabelWrong.json, back-end/resources/testing/wrong-types/testCheckLabelWrongInstruction.json, back-end/src/sciler/config/configHandler.go, back-end/src/sciler/config/configHandler_test.go, back-end/src/sciler/config/readConfigTypes.go, back-end/src/sciler/config/workingConfigTypes.go, back-end/src/sciler/config/workingConfigTypes_test.go, back-end/src/sciler/handler/handler_helper.go, back-end/src/sciler/handler/handler_test.go, back-end/src/sciler/handler/instruction_test.go
Closes GH-37
config now has a LabelMap with `label -> component{ID, Device}`, which generates componentInstructions in SendLabelInstruction()
TODO
=> 37 component labels

cc_library/example-scripts-js-scc/display-angular/package-lock.json, cc_library/example-scripts-js-scc/display-angular/package.json, cc_library/example-scripts-js-scc/display-angular/src/app/app.component.ts, cc_library/example-scripts-js-scc/display-node/browser-side.js, cc_library/example-scripts-js-scc/display-node/bundle.js, cc_library/js-scc/.prettier.config.js, cc_library/js-scc/README.md, cc_library/js-scc/index.js, cc_library/js-scc/package.json
Fixed bug by allowing start to have a callback function
Updated and extends the documentation
Closes GH-172
=> 172 bug js scc connect + documentation

cc_library/README.md, front-end/src/app/camera/camera.component.html, front-end/src/app/components/device/device.component.html, front-end/src/app/components/device/device.component.ts, front-end/src/app/components/hint/hint.component.html, front-end/src/app/components/puzzle/puzzle.component.html, front-end/src/app/components/puzzle/puzzle.component.spec.ts, front-end/src/app/components/puzzle/puzzle.component.ts
closes gh-196
- puzzle button disabled unless game is started (general timer is active)
- full dutch 
- buttons in front-end are now bold
=> front-end in dutch

README.md
Update badge to the new main branch
=> Sig master

cc_library/example_scripts_js_scc/display-node/bundle.js, cc_library/example_scripts_js_scc/display-node/package-lock.json, cc_library/example_scripts_js_scc/display-node/package.json, cc_library/js_scc/README.md, cc_library/js_scc/index.js, cc_library/js_scc/package-lock.json, cc_library/js_scc/package.json
Added link to readme of the javascript library to the example scripts
Published to npm
Closes #208
=> 208 example link

back-end/resources/testing/test_doubleIDs.json, back-end/src/sciler/config/checkConfig.go, back-end/src/sciler/config/configHandler.go, back-end/src/sciler/config/configHandler_test.go
closes GH-201
unique id's across units
=> tests for unique ids across units

back-end/src/sciler/handler/handler.go, back-end/src/sciler/handler/handler_helper.go, back-end/src/sciler/handler/status_test.go, back-end/src/sciler/main.go
panics and raw messages are now printed
=> bugs finding made easier

.travis.yml, back-end/src/sciler/handler/instruction_test.go, cc_library/py_scc/sciler/app.py, cc_library/py_scc/setup.py, front-end/package-lock.json
fixed issue when an instruction is performed the logging crashes.
Now multiple instructions in 1 message can be performed without error
Uploaded tot PyPi
=> fixed error when logging bug

back-end/src/sciler/handler/handler.go
timers worden nu gestopt op reset
closes #232
=> timer reset bug

cc_library/example_scripts_js_scc/display-angular/package-lock.json, cc_library/example_scripts_py_scc/display.py, cc_library/example_scripts_py_scc/hue_lights.py, cc_library/example_scripts_py_scc/keypad.json, cc_library/example_scripts_py_scc/keypad.py, cc_library/example_scripts_py_scc/scanner.json, cc_library/example_scripts_py_scc/scanner.py
Added barcode scanner
Updated keypad to remember the last two inputs
=> Demo scanner

back-end/src/sciler/config/configHandler.go, back-end/src/sciler/handler/handler.go, back-end/src/sciler/handler/handler_helper.go, back-end/src/sciler/handler/handler_test.go, back-end/src/sciler/handler/instruction_test.go, back-end/src/sciler/handler/status_test.go, front-end/src/app/app.component.ts, front-end/src/app/components/device/device.component.html, front-end/src/app/components/device/device.component.ts, front-end/src/app/components/device/device.spec.ts, front-end/src/app/components/device/device.ts, front-end/src/app/components/device/devices.spec.ts, front-end/src/app/components/event/event.component.html, front-end/src/app/components/hint/hint.component.ts, front-end/src/app/components/puzzle/puzzle.component.html, front-end/src/assets/css/main.css
- cannot execute rule manually when it is executed
- fixed undefined bug front-end
- hint log tracked through front-end device status, so also accesible to back-end
closes #224, closes #223
=> rule execution button, bug fix and hint log

back-end/resources/production/Demo_presentation.json.default, back-end/resources/testing/test_conditions_array_of_object.json, back-end/resources/testing/test_conditions_array_of_operator.json, back-end/resources/testing/test_conditions_list_object.json, back-end/resources/testing/test_constraints_array_of_object.json, back-end/resources/testing/test_constraints_array_of_operator.json, back-end/resources/testing/test_constraints_list_object.json, back-end/resources/testing/test_constraints_operator_int.json, back-end/src/sciler/config/configHandler.go, back-end/src/sciler/config/configHandler_test.go, back-end/src/sciler/handler/confirmation_test.go, back-end/src/sciler/handler/handler.go, back-end/src/sciler/handler/handler_helper.go, back-end/src/sciler/handler/handler_test.go, back-end/src/sciler/handler/status_test.go, front-end/src/app/app.component.ts, front-end/src/app/components/device/devices.spec.ts, front-end/src/app/components/hint/hint.component.ts, front-end/src/app/config/config.component.html
all casting cases in handler and config handler are checked first to avoid crashes.
closes #229
=> no back-end crash 

front-end/src/app/components/device/device.component.css, front-end/src/app/components/device/device.component.html
bug due to old propertyname
- showing status again
- fixed the length of long words without spaces
=> fixed component bug

back-end/README.md, broker/README.md, front-end/README.md
Updated documentation for setting up devices and the Sciler system on a Raspberry pi
=> Documentation update

back-end/resources/manuals/room_manual.md, back-end/resources/testing/test_equals_with_typo.json, back-end/src/sciler/config/checkConfig.go, back-end/src/sciler/config/workingConfigTypes.go, back-end/src/sciler/config/workingConfigTypes_test.go, back-end/src/sciler/handler/handler_test.go
`eqwt` and `not eqwt` added as comparison options
added tests
updated documentation
=> eqwt and not eqwt implemented

back-end/src/sciler/communication/communication_test.go, back-end/src/sciler/handler/instruction_test.go, back-end/src/sciler/main.go, front-end/karma.conf.js, front-end/package-lock.json, front-end/package.json, front-end/src/app/components/manage/manage.component.spec.ts, front-end/src/app/message.ts
Ik heb het logging level naar Panic gezet, dan wordt er alleen een logfile aangemaakt als SCILER daadwerkelijk crasht
Ook is 1 test geupdate zodat die weer werkte met de test environment die geupdate is.
=> Logging uitzetten
